# Generated by Django 4.0 on 2021-12-29 18:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('acquisition_date', models.DateField()),
                ('kilometers', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty', models.BooleanField()),
                ('total_workmanship', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('cnp', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='CNP-ul trebuie sa aiba lungimea 13si sa fie format din cifre.', regex='^[0-9]{13}$')])),
                ('birthday', models.DateField()),
                ('registration_date', models.DateField()),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workmanship', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField()),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceAPI.car')),
                ('card_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ServiceAPI.card')),
            ],
        ),
    ]
