# Generated by Django 4.0 on 2021-12-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='card_id',
            new_name='card',
        ),
    ]
